services:
  seerr-catalog:
    image: ghcr.io/aerya/stremio-seerr-catalog:latest
    container_name: seerr-catalog
    ports:
      - "7000:7000"
    env_file:
      - .env
    environment:
      - BASE_URL=${BASE_URL}
      - API_KEY=${API_KEY}
      - PORT=${PORT}
      - HOST=${HOST}
      - TMDB_API_KEY=${TMDB_API_KEY}
    volumes:
      - /mnt/Docker/stremio/seerrcatalog:/app/data
    restart: always
